### PR TITLE
Update Form1.cs

### PR DESCRIPTION
**Pull request by BobN16**
James, 

This is the completed change for the CT Message change for version 7.02 which still supports the previous 10 tones per port. I have tested this with several dat files. I believe this to be the only code change that was needed besides your previous change to use multiple XML files. That was genius.

Thank you the heads up on the conversion.
Bob

### CODE REVIEW

**Comment by bolwire** [comment]
Hi Bob,

Can you give me a little more detail on what the change is in 7.02 that requires this change is and how it is different from previous versions. Unfortunately I no longer have an RC210 and I don't keep up to date.

**Comment by BobN16** [comment]
James,

 

I am attaching the README.txt file that accompanied the version 7.02 release which has Ken’s explanation of the change. It also contains all the changes back before 5.281. As I see it, prior to 7.02 there were about 240 selections (3 ports with 10 tone selections with 2 tones for each of 4 segments) to parse. Starting with 7.02 there is just one pool of 10 tones with 4 segments of 2 tones. So the change was to set one pass through the 10 tones for 7.02 but allow the 3 passes for all other versions. And it just occurred to me that the “if fwVersion” should be “if fwVersion >= 7.02” to accommodate the future.

 

I am also attaching the rc210.dat file I have been using for testing. If you use notepad or notepad++ and compare this file to a version 6 file, the Dwnld file attached, you will see the difference in the files in the [Courtesy] section. Also note that the first section of the file also has a flag to show it has been converted by version 7.02. this was the remapping macros as a bunch of shuffling occurred with 7.02. Of course those changes are in the XML files.

**Comment by bolwire** [comment]
Hi Bob,

Thanks for the info. I've reworked the changes just a bit. I moved the fwVersion variable to the top of the method so that if needed in the future it can be referenced anywhere in the method.

I've also changed the logic. The new logic will start as it did in the past, however after the first iteration of ports, if the fwVersion is >= 7.02 instead of moving to the next iteration it will break out of the loop.

I've also added a simple MessageBox to alert the user when the .dat file referenced in _datFilename variable cannot be found when the Generate_Report method is called. I don't know why this would ever happen, but if it does, the user will know why no report was made.

If you could look over the changed and possibly give it a try (I didn't get the .dat attachment, you might try to email it to me directly, or submit it on the group forum). I've already pushed the changed to my master.

**Comment by bolwire** [comment]
Closing PR, needed changes have been made

**Pull request closed without merging**
